services:
  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db-data:
